<?php

const ADMIN_THEME_NAME = 'blue';

function admin_theme()
{
    $themes = [
        'blue' => [
            'body' => 'bg-blue-50 text-slate-950',
            'sidebar_border' => 'border-blue-200',
            'soft_bg' => 'bg-blue-50',
            'brand_bg' => 'bg-blue-600',
            'brand_text' => 'text-slate-950',
            'muted_text' => 'text-blue-700',
            'section_text' => 'text-blue-500',
            'nav_active' => 'bg-blue-50 text-blue-700',
            'nav_idle' => 'text-slate-700 hover:bg-blue-100 hover:text-blue-950',
            'nav_icon_active' => 'text-blue-700',
            'nav_icon_idle' => 'text-slate-500',
            'link' => 'text-blue-700 hover:text-blue-950',
            'date_badge' => 'border-blue-200 bg-white text-blue-700',
            'primary_button' => 'bg-blue-600 hover:bg-blue-700',
            'hover_bg' => 'hover:bg-blue-100',
            'css' => [
                'bg' => '#eff6ff',
                'card' => '#ffffff',
                'border' => '#bfdbfe',
                'muted' => '#1d4ed8',
                'ink' => '#0f172a',
                'primary' => '#2563eb',
                'primary_light' => '#60a5fa',
                'primary_dark' => '#1d4ed8',
                'button_start' => '#3b82f6',
                'button_end' => '#2563eb',
                'button_hover_start' => '#2563eb',
                'button_hover_end' => '#1d4ed8',
                'ring' => 'rgba(37, 99, 235, .16)',
                'shadow' => 'rgba(37, 99, 235, .12)',
            ],
        ],
        'saffron' => [
            'body' => 'bg-orange-50 text-orange-950',
            'sidebar_border' => 'border-orange-200',
            'soft_bg' => 'bg-orange-50',
            'brand_bg' => 'bg-orange-600',
            'brand_text' => 'text-orange-950',
            'muted_text' => 'text-orange-700',
            'section_text' => 'text-orange-500',
            'nav_active' => 'bg-orange-600 text-white shadow-sm',
            'nav_idle' => 'text-orange-900 hover:bg-orange-100 hover:text-orange-950',
            'nav_icon_active' => 'bg-white/20 text-white',
            'nav_icon_idle' => 'bg-white text-orange-600 ring-1 ring-orange-200',
            'link' => 'text-orange-700 hover:text-orange-950',
            'date_badge' => 'border-orange-200 bg-white text-orange-700',
            'primary_button' => 'bg-orange-600 hover:bg-orange-700',
            'hover_bg' => 'hover:bg-orange-100',
            'css' => [
                'bg' => '#fff7ed',
                'card' => '#ffffff',
                'border' => '#fed7aa',
                'muted' => '#9a3412',
                'ink' => '#2f1608',
                'primary' => '#ea580c',
                'primary_light' => '#fb923c',
                'primary_dark' => '#c2410c',
                'button_start' => '#f97316',
                'button_end' => '#ea580c',
                'button_hover_start' => '#ea580c',
                'button_hover_end' => '#c2410c',
                'ring' => 'rgba(234, 88, 12, .18)',
                'shadow' => 'rgba(194, 65, 12, .12)',
            ],
        ],
        'slate' => [
            'body' => 'bg-slate-50 text-slate-950',
            'sidebar_border' => 'border-slate-200',
            'soft_bg' => 'bg-slate-50',
            'brand_bg' => 'bg-slate-950',
            'brand_text' => 'text-slate-950',
            'muted_text' => 'text-slate-500',
            'section_text' => 'text-slate-400',
            'nav_active' => 'bg-slate-950 text-white shadow-sm',
            'nav_idle' => 'text-slate-600 hover:bg-slate-100 hover:text-slate-950',
            'nav_icon_active' => 'bg-white/15 text-white',
            'nav_icon_idle' => 'bg-white text-slate-500 ring-1 ring-slate-200',
            'link' => 'text-slate-700 hover:text-slate-950',
            'date_badge' => 'border-slate-200 bg-white text-slate-500',
            'primary_button' => 'bg-slate-950 hover:bg-slate-800',
            'hover_bg' => 'hover:bg-slate-100',
            'css' => [
                'bg' => '#f8fafc',
                'card' => '#ffffff',
                'border' => '#e2e8f0',
                'muted' => '#64748b',
                'ink' => '#0f172a',
                'primary' => '#0f172a',
                'primary_light' => '#94a3b8',
                'primary_dark' => '#020617',
                'button_start' => '#0f172a',
                'button_end' => '#1e293b',
                'button_hover_start' => '#1e293b',
                'button_hover_end' => '#020617',
                'ring' => 'rgba(15, 23, 42, .10)',
                'shadow' => 'rgba(15, 23, 42, .08)',
            ],
        ],
    ];

    return $themes[ADMIN_THEME_NAME] ?? $themes['blue'];
}
